services:
  php:
    container_name: php_docker
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 80:80
    volumes:
      - ./www:/var/www/html/

  db:
    container_name: db_docker
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - 3306:3306
    volumes:
      - ./db:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin_docker
    ports:
      - 8080:80
    environment:
      PMA_HOST: db
      PMA_PORT: 3306

volumes:
  db-data:
    driver: local
